#!/usr/bin/env bash

EXP="$1"
SRC=$(mktemp -u "/tmp/XXXX-exp")
SRC_C="${SRC}.c"
SRC_SO="${SRC}.so"

cat <<__EOF__ >"${SRC_C}"
/* Generated by fourier.sh */
#include <math.h>

double f(double x)
{
	return $EXP;
}
__EOF__

cc -lm -shared -fPIC "${SRC_C}" -o "${SRC_SO}"
bin/_fouriersolver "${SRC_SO}" "${@:2}"
rm -rf "${SRC_SO}"
